<a href="https://colab.research.google.com/github/gott51010/zhenXiang/blob/master/xx%E7%81%AB%E7%82%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch
torch.__version__

'1.7.0+cu101'

In [4]:
x = torch.empty(5,3)

In [5]:
x

tensor([[3.2863e-35, 0.0000e+00, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3788e-14, 1.8369e+28, 1.9433e-19],
        [3.3738e-12, 7.4086e+28, 6.9397e+22],
        [1.7260e+25, 2.2856e+20, 5.0948e-14]])

In [6]:
x = torch.rand(5,3)

In [7]:
x

tensor([[0.7248, 0.4810, 0.0284],
        [0.7503, 0.6397, 0.2915],
        [0.4666, 0.1847, 0.1388],
        [0.5711, 0.6253, 0.8228],
        [0.9728, 0.1579, 0.4765]])

In [9]:
x = torch.zeros(5,3,dtype=torch.long)

In [10]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [12]:
x = torch.tensor([555,3.3])
x

tensor([555.0000,   3.3000])

In [13]:
x = x.new_ones(5, 3, dtype=torch.float64) 
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [14]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.9103,  0.4504,  0.0096],
        [ 0.7740,  1.2200,  1.2668],
        [-1.1789, -0.0970,  0.1892],
        [-2.5442,  0.2846,  0.7140],
        [ 0.6550,  0.5176,  0.1504]])

In [17]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [18]:
x

tensor([[-0.9103,  0.4504,  0.0096],
        [ 0.7740,  1.2200,  1.2668],
        [-1.1789, -0.0970,  0.1892],
        [-2.5442,  0.2846,  0.7140],
        [ 0.6550,  0.5176,  0.1504]])

In [24]:
y = torch.rand(5, 3)
y

tensor([[0.4436, 0.0431, 0.5184],
        [0.5279, 0.5360, 0.2741],
        [0.1370, 0.8664, 0.5792],
        [0.0980, 0.4981, 0.8555],
        [0.0256, 0.1700, 0.6799]])

In [25]:
print( x + y)

tensor([[-0.4666,  0.4936,  0.5279],
        [ 1.3019,  1.7560,  1.5409],
        [-1.0419,  0.7694,  0.7684],
        [-2.4462,  0.7827,  1.5695],
        [ 0.6806,  0.6876,  0.8303]])


In [26]:
torch.add(x, y)

tensor([[-0.4666,  0.4936,  0.5279],
        [ 1.3019,  1.7560,  1.5409],
        [-1.0419,  0.7694,  0.7684],
        [-2.4462,  0.7827,  1.5695],
        [ 0.6806,  0.6876,  0.8303]])

In [27]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.4666,  0.4936,  0.5279],
        [ 1.3019,  1.7560,  1.5409],
        [-1.0419,  0.7694,  0.7684],
        [-2.4462,  0.7827,  1.5695],
        [ 0.6806,  0.6876,  0.8303]])


In [37]:
result = torch.empty(5, 3, dtype=torch.float64)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.1795,  4.9008,  4.0191],
        [ 1.8637,  3.6704,  3.2764],
        [-0.0891,  2.3534,  2.1988],
        [-1.4544,  2.7350,  2.7236],
        [ 1.7447,  2.9680,  2.1599]], dtype=torch.float64)


In [43]:
x

tensor([[ 2.0897,  3.4504,  3.0096],
        [ 0.7740,  1.2200,  1.2668],
        [-1.1789, -0.0970,  0.1892],
        [-2.5442,  0.2846,  0.7140],
        [ 0.6550,  0.5176,  0.1504]])

In [53]:
 x[0, :]

tensor([2.0897, 3.4504, 3.0096])

In [51]:
import copy

In [52]:
y = copy.deepcopy(x[0, :])
y += 1
print(y)
print(x[0, :])

tensor([3.0897, 4.4504, 4.0096])
tensor([2.0897, 3.4504, 3.0096])


In [54]:
x

tensor([[ 2.0897,  3.4504,  3.0096],
        [ 0.7740,  1.2200,  1.2668],
        [-1.1789, -0.0970,  0.1892],
        [-2.5442,  0.2846,  0.7140],
        [ 0.6550,  0.5176,  0.1504]])

In [55]:
y = x.view(15)

In [56]:
y

tensor([ 2.0897,  3.4504,  3.0096,  0.7740,  1.2200,  1.2668, -1.1789, -0.0970,
         0.1892, -2.5442,  0.2846,  0.7140,  0.6550,  0.5176,  0.1504])

In [57]:
y2 = x.view(-1,5)

In [58]:
y2

tensor([[ 2.0897,  3.4504,  3.0096,  0.7740,  1.2200],
        [ 1.2668, -1.1789, -0.0970,  0.1892, -2.5442],
        [ 0.2846,  0.7140,  0.6550,  0.5176,  0.1504]])

In [59]:
print(x.size(), y.size(), y2.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [60]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 1.0897,  2.4504,  2.0096],
        [-0.2260,  0.2200,  0.2668],
        [-2.1789, -1.0970, -0.8108],
        [-3.5442, -0.7154, -0.2860],
        [-0.3450, -0.4824, -0.8496]])
tensor([ 2.0897,  3.4504,  3.0096,  0.7740,  1.2200,  1.2668, -1.1789, -0.0970,
         0.1892, -2.5442,  0.2846,  0.7140,  0.6550,  0.5176,  0.1504])


In [62]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3436])
-0.3435654938220978


In [63]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])
